'use client';
import { useEffect, useMemo, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, BarChart3, BookImage, Boxes, Check, CheckCircle2, ChevronDown, CircleHelp, Clapperboard, Cloud, Copy, Download, Eye, FileImage, FileJson, FolderOpen, Gauge, ImagePlus, Layers3, LayoutDashboard, Link2, LoaderCircle, Menu, Palette, Play, Plus, ScanSearch, Settings2, ShieldCheck, Sparkles, WandSparkles, X, Zap } from 'lucide-react';
import { CHANNELS, DIRECTIONS, readiness, type ChannelId, type DirectionId, type SavedCampaign } from '../lib/campaign';
import { uploadToCloudinary, transformUrl, type CloudAsset } from '../lib/cloudinary';
import MotionEditor from '../components/MotionEditor';

type Tab='overview'|'studio'|'brand'|'library'|'motion'|'insights';
type BrandKit={name:string;tagline:string;color:string;logo:string};
const defaultBrand:BrandKit={name:'AeroBeat',tagline:'Feel the Sound. Live the Moment.',color:'#67e8f9',logo:''};
const copyIdeas=(product:string,details:string)=>[`${product}: Made for every moment.`,`${product} — elevate your everyday.`,`Meet ${product}. Discover a new perspective.`];

function makeCreative(source:string,w:number,h:number,data:{product:string;brand:string;tagline:string;headline:string;cta:string;details:string;direction:DirectionId;color:string;logo:string;channel:string}):Promise<Blob>{
 return new Promise((resolve,reject)=>{
  const img=new Image();
  img.onload=()=>{
   const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;
   const c=canvas.getContext('2d');if(!c){reject(new Error('Canvas is not available'));return;}
   const direction=DIRECTIONS.find(x=>x.id===data.direction)||DIRECTIONS[0];
   const vertical=h/w>1.35;
   const landscape=w/h>1.3;
   const square=!vertical&&!landscape;
   const min=Math.min(w,h);
   const pad=Math.round(min*(vertical?.065:landscape?.065:.07));
   const accent=/^#[0-9a-f]{6}$/i.test(data.color)?data.color:'#67e8f9';

   // Premium dark editorial background with restrained light, not a white product mat.
   const bg=c.createLinearGradient(0,0,w,h);
   bg.addColorStop(0,direction.bg);
   bg.addColorStop(1,'#071522');
   c.fillStyle=bg;c.fillRect(0,0,w,h);
   const glow=c.createRadialGradient(w*.78,h*.16,0,w*.78,h*.16,min*.95);
   glow.addColorStop(0,`${accent}35`);glow.addColorStop(1,'transparent');
   c.fillStyle=glow;c.fillRect(0,0,w,h);
   c.globalAlpha=.07;c.strokeStyle=accent;c.lineWidth=Math.max(1,min/900);
   for(let x=pad;x<w;x+=Math.max(42,min*.11)){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}
   c.globalAlpha=1;

   let imageBox:{x:number;y:number;w:number;h:number};
   let textX:number,textY:number,textW:number,titleSize:number,bodySize:number,brandSize:number,ctaY:number;
   if(vertical){
    imageBox={x:pad,y:pad*.72,w:w-pad*2,h:h*.32};
    textX=pad;textY=imageBox.y+imageBox.h+pad*.78;textW=w-pad*2;
    titleSize=Math.round(min*.078);bodySize=Math.round(min*.026);brandSize=Math.round(min*.022);ctaY=Math.round(h*.81);
   }else if(landscape){
    imageBox={x:w*.585,y:h*.105,w:w*.345,h:h*.79};
    textX=pad;textY=h*.205;textW=w*.46;
    titleSize=Math.round(min*.078);bodySize=Math.round(min*.031);brandSize=Math.round(min*.026);ctaY=h-pad*1.32;
   }else{
    imageBox={x:w*.12,y:h*.065,w:w*.76,h:h*.405};
    textX=pad;textY=imageBox.y+imageBox.h+pad*.55;textW=w-pad*2;
    titleSize=Math.round(min*.073);bodySize=Math.round(min*.025);brandSize=Math.round(min*.022);ctaY=h-pad*1.3;
   }

   // A subtle dark image well preserves the source image without the oversized white frame.
   c.save();c.shadowColor='#00000066';c.shadowBlur=min*.025;c.shadowOffsetY=min*.009;
   c.fillStyle='#0a1421';roundRect(c,imageBox.x,imageBox.y,imageBox.w,imageBox.h,Math.round(min*.025));c.fill();c.restore();
   c.save();roundRect(c,imageBox.x,imageBox.y,imageBox.w,imageBox.h,Math.round(min*.025));c.clip();
   const inset=Math.min(imageBox.w,imageBox.h)*.035;
   const scale=Math.min((imageBox.w-inset*2)/img.width,(imageBox.h-inset*2)/img.height);
   const iw=img.width*scale,ih=img.height*scale;
   c.drawImage(img,imageBox.x+(imageBox.w-iw)/2,imageBox.y+(imageBox.h-ih)/2,iw,ih);
   c.restore();
   c.strokeStyle='#ffffff20';c.lineWidth=Math.max(1,min*.0015);roundRect(c,imageBox.x,imageBox.y,imageBox.w,imageBox.h,Math.round(min*.025));c.stroke();

   const brandLabel=(data.logo||data.brand||'').trim().toUpperCase().slice(0,24);
   c.textBaseline='top';c.fillStyle='#8BEAFF';c.font=`700 ${brandSize}px Arial`;
   c.fillText(brandLabel,textX,textY, textW);
   let y=textY+brandSize*1.8;
   const titleLine=Math.round(titleSize*1.08);
   const titleLines=drawWrapped(c,data.headline||data.product||'Discover something better',textX,y,textW,titleLine,titleSize,'800',direction.ink,vertical?2:2);
   y+=titleLines*titleLine+Math.round(min*.025);
   const bodyLine=Math.round(bodySize*1.42);
   const bodyMax=vertical?4:landscape?3:3;
   drawWrapped(c,data.details||data.tagline||'Designed for the moments that matter.',textX,y,textW,bodyLine,bodySize,'500',direction.muted,bodyMax);

   // Keep the CTA in a reserved footer zone, with a bounded pill and readable contrast.
   const cta=(data.cta||'Discover now').trim().slice(0,35);
   const ctaFont=Math.max(14,Math.round(min*.025));
   const pillH=Math.max(42,Math.round(min*.075));
   c.font=`700 ${ctaFont}px Arial`;
   const pillW=Math.min(textW,Math.max(min*.25,c.measureText(cta).width+pad*.55));
   const pillX=textX;
   c.fillStyle=accent;roundRect(c,pillX,ctaY,pillW,pillH,pillH/2);c.fill();
   c.fillStyle='#FFFFFF';c.textBaseline='middle';c.font=`700 ${ctaFont}px Arial`;
   c.fillText(cta,pillX+pad*.22,ctaY+pillH/2,pillW-pad*.44);
   c.fillStyle='#d4e4f0b8';c.textBaseline='alphabetic';c.font=`500 ${Math.max(10,Math.round(min*.012))}px Arial`;
   c.fillText(`${data.channel.toUpperCase()}  ·  ${w} × ${h}`,pad,h-pad*.24);
   canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Could not render creative')),'image/jpeg',.94);
  };
  img.onerror=()=>reject(new Error('The source image could not be opened for creative rendering.'));
  img.src=source;
 });
}
function roundRect(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){c.beginPath();c.roundRect(x,y,w,h,r);}
function drawWrapped(c:CanvasRenderingContext2D,text:string,x:number,y:number,maxW:number,lineH:number,fontSize:number,weight:string,color:string,maxLines:number){
 c.font=`${weight} ${fontSize}px Arial`;c.fillStyle=color;c.textBaseline='top';const words=text.trim().split(/\s+/);let lines:string[]=[];let line='';
 for(const word of words){const test=line?`${line} ${word}`:word;if(c.measureText(test).width>maxW&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);
 if(lines.length>maxLines){lines=lines.slice(0,maxLines);let last=lines[maxLines-1];while(last&&c.measureText(`${last}…`).width>maxW)last=last.slice(0,-1);lines[maxLines-1]=last.trimEnd()+'…';}
 lines.forEach((item,i)=>c.fillText(item,x,y+i*lineH,maxW));return lines.length;
}

export default function Home(){
 const [tab,setTab]=useState<Tab>('overview'); const [asset,setAsset]=useState<CloudAsset|null>(null); const [localPreview,setLocalPreview]=useState(''); const [product,setProduct]=useState('AeroBeat Pro'); const [details,setDetails]=useState('Premium wireless over-ear headphones designed for everyday listening, featuring soft cushioned ear pads, an adjustable headband and a foldable design.'); const [brand,setBrand]=useState<BrandKit>(defaultBrand); const [direction,setDirection]=useState<DirectionId>('Future Forward'); const [headline,setHeadline]=useState('Sound Beyond Limits.'); const [cta,setCta]=useState('Experience AeroBeat Pro'); const [audience,setAudience]=useState('Young professionals, students, music enthusiasts and technology lovers'); const [objective,setObjective]=useState('Product awareness and online sales'); const [channels,setChannels]=useState<string[]>(['Instagram','Instagram Story','LinkedIn','E-commerce','Website Hero','Email Banner']); const [uploads,setUploads]=useState<{channel:string,url:string,w:number,h:number}[]>([]); const [busy,setBusy]=useState(false); const [progress,setProgress]=useState(''); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [campaigns,setCampaigns]=useState<SavedCampaign[]>([]); const [mobileMenu,setMobileMenu]=useState(false); const [search,setSearch]=useState(''); const [compare,setCompare]=useState(false); const [motionUrl,setMotionUrl]=useState(''); const [videoAsset,setVideoAsset]=useState<CloudAsset|null>(null); const [videoBusy,setVideoBusy]=useState(false); const videoRef=useRef<HTMLInputElement>(null); const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{setCampaigns(JSON.parse(localStorage.getItem('lr_campaigns')||'[]'));const b=localStorage.getItem('lr_brand');if(b)setBrand(JSON.parse(b));}catch{ /* ignore corrupt local cache */}},[]);
 useEffect(()=>{localStorage.setItem('lr_campaigns',JSON.stringify(campaigns));},[campaigns]);useEffect(()=>{localStorage.setItem('lr_brand',JSON.stringify(brand));},[brand]);
 const stats=useMemo(()=>readiness({asset:!!asset,name:product,details,brand:brand.name,channels,uploaded:uploads.length}),[asset,product,details,brand,channels,uploads]);
 const activeDirection=DIRECTIONS.find(x=>x.id===direction)!;
 const setFile=async(file?:File)=>{if(!file)return;setError('');setUploads([]);if(!file.type.startsWith('image/')){setError('Please choose a JPG, PNG or WEBP image.');return;}if(file.size>10*1024*1024){setError('Please use an image smaller than 10 MB for the free-plan-friendly workflow.');return;}const preview=URL.createObjectURL(file);setLocalPreview(preview);setProgress('Uploading original image to Cloudinary…');setBusy(true);try{const uploaded=await uploadToCloudinary(file,file.name);setAsset(uploaded);setNotice('Original product image uploaded to Cloudinary. Your source remains untouched.');}catch(e){setAsset(null);setError(e instanceof Error?e.message:'Upload failed.');}finally{setBusy(false);setProgress('');}};
 const toggleChannel=(id:string)=>{setChannels(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);setUploads([]);};
 const makeCampaign=async()=>{if(!asset||!localPreview){setError('Upload a product image first.');setTab('studio');return;}if(!channels.length){setError('Choose at least one output channel.');return;}setError('');setNotice('');setBusy(true);setUploads([]);try{const results=[] as {channel:string,url:string,w:number,h:number}[];for(let i=0;i<channels.length;i++){const spec=CHANNELS.find(x=>x.id===channels[i]);if(!spec)continue;setProgress(`Designing ${spec.id} creative (${i+1}/${channels.length})…`);const blob=await makeCreative(localPreview,spec.w,spec.h,{product,brand:brand.name,tagline:brand.tagline,headline,cta,details,direction,color:brand.color,logo:brand.logo,channel:spec.id});setProgress(`Delivering ${spec.id} through Cloudinary (${i+1}/${channels.length})…`);const uploaded=await uploadToCloudinary(blob,`${product.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${spec.id.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,'launchready/campaigns');results.push({channel:spec.id,url:uploaded.secure_url,w:spec.w,h:spec.h});setUploads([...results]);}setNotice(`Campaign complete: ${results.length} Cloudinary creatives generated.`);setTab('studio');}catch(e){setError(e instanceof Error?e.message:'Creative generation failed.');}finally{setBusy(false);setProgress('');}};
 const saveCampaign=()=>{if(!asset||!uploads.length){setError('Generate your Cloudinary creatives before saving the campaign.');return;}const item:SavedCampaign={id:crypto.randomUUID(),name:product,brand:brand.name,createdAt:new Date().toISOString(),assetUrl:asset.secure_url,creatives:uploads,direction,headline};setCampaigns(x=>[item,...x]);setNotice('Campaign saved to your local Campaign Library.');};
 const downloadManifest=()=>{const payload={product,brand,details,audience,objective,direction,headline,cta,source:asset?.secure_url,creatives:uploads,readiness:stats,createdAt:new Date().toISOString(),note:'Readiness is a deterministic checklist, not an independent AI quality assessment.'};downloadBlob(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),`${slug(product)}-campaign-manifest.json`);};
 const downloadAll=async()=>{if(!uploads.length)return;setBusy(true);setProgress('Preparing campaign downloads…');try{for(let i=0;i<uploads.length;i++){const u=uploads[i];const response=await fetch(u.url);if(!response.ok)throw new Error(`Could not download ${u.channel} creative (${response.status}). Open its Cloudinary asset link instead.`);const blob=await response.blob();downloadBlob(blob,`${slug(product)}-${slug(u.channel)}.jpg`);await new Promise(r=>setTimeout(r,250));}setNotice('All campaign creatives have been downloaded.');}finally{setBusy(false);setProgress('');}};
 const uploadVideo=async(file?:File)=>{if(!file)return;if(!file.type.startsWith('video/')){setError('Choose an MP4, MOV or WEBM video.');return;}if(file.size>50*1024*1024){setError('Please choose a video smaller than 50 MB.');return;}setError('');setVideoBusy(true);setProgress('Uploading video to Cloudinary…');try{const v=await uploadToCloudinary(file,file.name,'launchready/motion','video');setVideoAsset(v);setMotionUrl(v.secure_url.includes('/upload/')?v.secure_url.replace('/upload/','/upload/f_mp4,q_auto,vc_auto/') : v.secure_url);setNotice('Video uploaded to Cloudinary. Optimized MP4 delivery URL is ready.');}catch(e){setError(e instanceof Error?e.message:'Video upload failed. Check that your unsigned preset permits video uploads.');}finally{setVideoBusy(false);setProgress('');}};
 const menu=[['overview','Overview',LayoutDashboard],['studio','Creative Studio',WandSparkles],['brand','Brand Kit',Palette],['motion','Motion Ads',Clapperboard],['library','Campaign Library',FolderOpen],['insights','Campaign Intelligence',Activity]] as const;
 const shownCampaigns=campaigns.filter(c=>(c.name+' '+c.brand).toLowerCase().includes(search.toLowerCase()));
 return <main className="app-shell"><aside className={`sidebar ${mobileMenu?'open':''}`}><div className="side-brand"><div className="brand-symbol"><Sparkles size={19}/></div><span>LaunchReady <b>AI</b></span></div><div className="workspace-pill"><span className="avatar">LR</span><span><b>Creative workspace</b><small>Free plan workflow</small></span><ChevronDown size={14}/></div><div className="nav-caption">WORKSPACE</div><nav>{menu.map(([id,label,Icon])=><button key={id} className={`side-link ${tab===id?'active':''}`} onClick={()=>{setTab(id);setMobileMenu(false);}}><Icon size={18}/><span>{label}</span>{id==='library'&&campaigns.length>0&&<i>{campaigns.length}</i>}</button>)}</nav><div className="sidebar-bottom"><div className="cloud-status"><div className="cloud-icon"><Cloud size={17}/></div><div><b>Cloudinary delivery</b><small>{asset?'Source connected':'Awaiting source upload'}</small></div><span className={asset?'online':'offline'}/></div><div className="profile"><div className="profile-avatar">H</div><div><b>LaunchReady workspace</b><small>Product campaign builder</small></div><Settings2 size={16}/></div></div></aside>
 <section className="main-area"><header className="topbar"><button className="mobile-toggle" onClick={()=>setMobileMenu(!mobileMenu)}><Menu/></button><div className="breadcrumb">Workspace <span>/</span> {menu.find(x=>x[0]===tab)?.[1]}</div><div className="top-actions"><span className="plan-chip"><span/> Cloudinary-first · no external AI token</span><button className="icon-button" title="Help" onClick={()=>setNotice('Upload an image, choose a creative direction and channels, then generate Cloudinary-hosted campaign artwork.')}><CircleHelp size={17}/></button><button className="top-cta" onClick={()=>setTab('studio')}> <Plus size={16}/> New campaign</button></div></header>
 <div className="page-content">
 {tab==='overview'&&<><section className="welcome-row"><div><div className="eyebrow"><span className="live-dot"/> PRODUCT CAMPAIGN OPERATING SYSTEM</div><h1>Make your product<br/><span>the main character.</span></h1><p>One original image. A complete campaign system. Create, protect and deliver every creative through Cloudinary.</p><div className="welcome-actions"><button className="btn-primary" onClick={()=>setTab('studio')}>Open Creative Studio <ArrowRight size={17}/></button><button className="btn-quiet" onClick={()=>setTab('library')}>View campaigns <FolderOpen size={16}/></button></div></div><div className="hero-art"><div className="hero-art-glow"/><div className="hero-product-card">{localPreview?<img src={localPreview} alt="Uploaded product"/>:<div className="placeholder-product"><ImagePlus size={44}/><span>Your product<br/>starts here</span></div>}<div className="hero-art-tag"><Sparkles size={13}/> CREATIVE ENGINE</div></div><div className="floating-stat stat-a"><Gauge size={16}/><span><b>{stats.score}%</b><small>Readiness</small></span></div><div className="floating-stat stat-b"><Cloud size={16}/><span><b>Cloudinary</b><small>Media delivery</small></span></div></div></section>
 <div className="metrics-grid"><Metric icon={<ImagePlus/>} label="Source asset" value={asset?'Connected':'Not uploaded'} sub={asset?`${asset.width} × ${asset.height}`:'Upload to begin'}/><Metric icon={<Layers3/>} label="Creative outputs" value={String(uploads.length)} sub="Cloudinary-hosted assets"/><Metric icon={<Gauge/>} label="Campaign readiness" value={`${stats.score}%`} sub="Rule-based checklist"/><Metric icon={<FolderOpen/>} label="Saved campaigns" value={String(campaigns.length)} sub="Stored in this browser"/></div>
 <div className="section-head"><div><div className="eyebrow">YOUR WORKFLOW</div><h2>Everything to go from product to launch.</h2></div><button className="text-action" onClick={()=>setTab('studio')}>Start creating <ArrowRight size={15}/></button></div><div className="module-grid"><Module icon={<WandSparkles/>} title="Product Glow-Up" copy="Build platform-specific creatives with your product, brand, copy and visual direction." action="Open studio" onClick={()=>setTab('studio')} accent="purple"/><Module icon={<Palette/>} title="Brand Guardian" copy="Keep brand colors, logo, tone and campaign identity consistent." action="Configure brand" onClick={()=>setTab('brand')} accent="cyan"/><Module icon={<Clapperboard/>} title="Motion Ad Composer" copy="Prepare Cloudinary video delivery from supported media assets." action="Open motion studio" onClick={()=>setTab('motion')} accent="orange"/><Module icon={<ShieldCheck/>} title="Campaign preflight" copy="Check source, copy, brand, channel coverage and export completion." action="Review checklist" onClick={()=>setTab('insights')} accent="green"/></div>
 <div className="bottom-banner"><div className="banner-icon"><Zap/></div><div><b>One source. Every channel. One launch pack.</b><p>Preserve your original product image while generating reusable campaign assets.</p></div><button onClick={()=>setTab('studio')}>Build campaign <ArrowRight size={16}/></button></div></>}
 {tab==='studio'&&<><PageTitle kicker="PRODUCT GLOW-UP STUDIO" title="Build a campaign that looks like a brand." subtitle="Upload one product image, define your creative direction and render real, downloadable campaign artwork."/><div className="studio-layout"><div className="studio-main"><Panel number="01" title="Product source" subtitle="Upload the original product image to Cloudinary"><div className={`upload-zone ${asset?'has-asset':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void setFile(e.dataTransfer.files?.[0]);}} onClick={()=>fileRef.current?.click()}><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>void setFile(e.target.files?.[0])}/>{localPreview?<><img className="source-thumb" src={localPreview} alt="Source product"/><div className="upload-copy"><b>{asset?.public_id?.split('/').pop()||'Selected product image'}</b><small>{asset?`${asset.width} × ${asset.height} · ${(asset.bytes/1024/1024).toFixed(2)} MB · Cloudinary uploaded`:'Uploading original…'}</small><span>Click or drop to replace source</span></div><BadgeCheck className="upload-check"/></>:<><div className="upload-icon"><ImagePlus size={25}/></div><div className="upload-copy"><b>Drop your product image here</b><small>JPG, PNG or WEBP · maximum 10 MB</small><span>Browse files</span></div><ArrowDownToLine className="upload-arrow"/></>}</div><div className="micro-trust"><span><ShieldCheck size={13}/> Original preserved</span><span><Cloud size={13}/> Direct Cloudinary upload</span><span><Check size={13}/> No external AI token</span></div><div className="form-grid"><Field label="Product / campaign name"><input value={product} onChange={e=>setProduct(e.target.value)} placeholder="e.g. AeroBeat Pro"/></Field><Field label="Brand name"><input value={brand.name} onChange={e=>setBrand({...brand,name:e.target.value})} placeholder="Your brand"/></Field><Field label="Verified product details" wide><textarea value={details} onChange={e=>setDetails(e.target.value)} rows={3} placeholder="Describe only real product features and benefits."/></Field><Field label="Target audience"><input value={audience} onChange={e=>setAudience(e.target.value)}/></Field><Field label="Campaign objective"><select value={objective} onChange={e=>setObjective(e.target.value)}><option>Product awareness and online sales</option><option>New product launch</option><option>Lead generation</option><option>Seasonal promotion</option><option>Brand awareness</option></select></Field></div></Panel>
 <Panel number="02" title="Creative direction" subtitle="Choose a visual treatment, campaign headline and CTA"><div className="direction-grid">{DIRECTIONS.map(d=><button key={d.id} className={`direction-card ${direction===d.id?'selected':''}`} onClick={()=>{setDirection(d.id);setUploads([]);}}><div className="swatches"><i style={{background:d.bg}}/><i style={{background:d.accent}}/><i style={{background:d.ink}}/></div><b>{d.id}</b><small>{d.sub}</small>{direction===d.id&&<CheckCircle2 size={16} className="direction-check"/>}</button>)}</div><div className="form-grid"><Field label="Campaign headline" wide><input value={headline} onChange={e=>setHeadline(e.target.value)} maxLength={70}/></Field><Field label="Call to action"><input value={cta} onChange={e=>setCta(e.target.value)} maxLength={35}/></Field><Field label="Campaign tagline"><input value={brand.tagline} onChange={e=>setBrand({...brand,tagline:e.target.value})}/></Field></div><div className="copy-lab"><div className="copy-lab-head"><span><Sparkles size={15}/> Headline ideas</span><small>Editable copy suggestions · not AI-generated</small></div>{copyIdeas(product,details).map((s,i)=><button key={s} className={headline===s?'picked':''} onClick={()=>{setHeadline(s);setUploads([]);}}>{s}{headline===s&&<Check size={14}/>}</button>)}</div></Panel>
 <Panel number="03" title="Launch channels" subtitle="Select where this campaign needs to appear"><div className="channel-grid">{CHANNELS.map(c=><button key={c.id} className={`channel-chip ${channels.includes(c.id)?'on':''}`} onClick={()=>toggleChannel(c.id)}><span>{c.id}</span><small>{c.w} × {c.h}</small>{channels.includes(c.id)&&<Check size={14}/>}</button>)}</div><div className="channel-foot"><span>{channels.length} channels selected</span><button onClick={()=>setChannels(CHANNELS.map(c=>c.id))}>Select all</button><button onClick={()=>setChannels([])}>Clear</button></div></Panel>
 <div className="generate-row"><div><b>Ready to create your campaign?</b><small>Each selected creative is rendered, then uploaded to Cloudinary.</small></div><button className="btn-primary large" disabled={busy||!asset||!channels.length} onClick={()=>void makeCampaign()}>{busy?<><LoaderCircle className="spin"/> {progress||'Working…'}</>:<><WandSparkles size={17}/> Generate campaign assets</>}</button></div>
 {error&&<div className="alert error"><X size={16}/>{error}</div>}{notice&&<div className="alert success"><CheckCircle2 size={16}/>{notice}</div>}
 {uploads.length>0&&<Panel title="04 · Campaign creative outputs" subtitle={`${uploads.length} real Cloudinary assets · text and CTA are embedded in the exported images`}><div className="output-grid">{uploads.map(u=><div className="output-card" key={u.channel}><div className="output-preview"><img src={u.url} alt={`${product} ${u.channel} creative`}/></div><div className="output-meta"><b>{u.channel}</b><small>{u.w} × {u.h}</small></div><a href={u.url} target="_blank" rel="noreferrer" className="open-asset"><Eye size={14}/> Open Cloudinary asset <ArrowRight size={13}/></a></div>)}</div><div className="export-toolbar"><div><b>Campaign export pack</b><small>Manifest includes source URL, channel sizes, copy and delivery links.</small></div><button className="btn-secondary" onClick={saveCampaign}><Plus size={15}/> Save campaign</button><button className="btn-secondary" onClick={downloadManifest}><FileJson size={15}/> Manifest</button><button className="btn-primary" onClick={()=>void downloadAll()}><Download size={15}/> Download creatives</button></div></Panel>}</div>
 <aside className="studio-aside"><div className="side-panel"><div className="aside-heading"><span>LIVE CAMPAIGN PREVIEW</span><span className="live-dot"/></div>{localPreview?<div className="creative-live" style={{background:activeDirection.bg,color:activeDirection.ink}}><div className="live-top" style={{color:brand.color}}>{brand.name}</div><div className="live-middle"><div><small>{brand.name.toUpperCase()}</small><h3>{headline}</h3><p>{details.slice(0,125)}</p><b style={{background:brand.color,color:'#07111e'}}>{cta}</b></div><img src={localPreview} alt="Product preview"/></div><span className="live-foot">{direction} · product image preserved</span></div>:<div className="preview-empty"><ImagePlus size={28}/><b>Your creative preview appears here</b><small>Upload a product image to begin.</small></div>}<div className="preview-data"><div><small>ACTIVE DIRECTION</small><b>{direction}</b></div><div><small>PRODUCT</small><b>{product||'—'}</b></div><div><small>ASSET SOURCE</small><b>{asset?'Cloudinary original':'Not uploaded'}</b></div></div></div><div className="side-panel score-panel"><div className="score-head"><div><small>CAMPAIGN READINESS</small><b>{stats.score}%</b></div><Gauge size={24}/></div><div className="progress-track"><i style={{width:`${stats.score}%`}}/></div><p>Rule-based checklist score. This is not an independent AI image-quality assessment.</p><div className="check-mini">{stats.checks.map(([label,ok])=><span key={label} className={ok?'ok':''}>{ok?<CheckCircle2 size={13}/>:<span className="empty-dot"/>}{label}</span>)}</div></div><div className="side-panel guardian"><ShieldCheck size={19}/><div><b>Product Consistency Guardian</b><p>Every output is rendered from the same uploaded source. Background removal and generated scene replacement are not silently simulated.</p></div></div></aside></div></>}
 {tab==='brand'&&<><PageTitle kicker="BRAND GUARDIAN" title="Make every campaign feel unmistakably yours." subtitle="Save a reusable brand kit and apply it to future campaign compositions."/><div className="brand-layout"><Panel title="Brand identity" subtitle="These settings are saved in this browser"><div className="form-grid"><Field label="Brand name"><input value={brand.name} onChange={e=>setBrand({...brand,name:e.target.value})}/></Field><Field label="Brand tagline"><input value={brand.tagline} onChange={e=>setBrand({...brand,tagline:e.target.value})}/></Field><Field label="Brand accent color"><div className="color-input"><input type="color" value={brand.color} onChange={e=>setBrand({...brand,color:e.target.value})}/><input value={brand.color} onChange={e=>setBrand({...brand,color:e.target.value})}/></div></Field><Field label="Logo text / wordmark"><input value={brand.logo} onChange={e=>setBrand({...brand,logo:e.target.value})} placeholder="Optional logo text"/></Field></div><div className="brand-preview" style={{'--brand-accent':brand.color} as CSSProperties}><small>BRAND PREVIEW</small><h2>{brand.name||'Your brand'}</h2><p>{brand.tagline}</p><span>{brand.logo||brand.name}</span></div></Panel><Panel title="Brand consistency checks" subtitle="Checks run against the campaign configuration"><div className="brand-checks">{[['Brand name present',!!brand.name],['Tagline available',!!brand.tagline],['Accent color selected',/^#[0-9a-f]{6}$/i.test(brand.color)],['Product source reused',!!asset],['Creative direction selected',!!direction]].map(([s,v])=><div key={String(s)}><span>{String(s)}</span>{v?<BadgeCheck className="green"/>:<span className="pending">Needs input</span>}</div>)}</div><p className="fineprint">This guardian validates campaign settings and source reuse. It does not use computer vision to verify logo or product pixels.</p></Panel></div></>}
 {tab==='motion'&&<><PageTitle kicker="MOTION AD STUDIO" title="Turn product footage into a campaign." subtitle="Trim your clip, add animated messaging, create camera movement, mix music and export platform-ready video through Cloudinary."/><MotionEditor videoAsset={videoAsset} motionUrl={motionUrl} videoBusy={videoBusy} onUploadVideo={file=>void uploadVideo(file)}/></>}
 {tab==='library'&&<><PageTitle kicker="CAMPAIGN LIBRARY" title="Every campaign, in one place." subtitle="Saved campaigns are stored in this browser. Their media remains hosted by Cloudinary."/><div className="library-tools"><div className="searchbox"><ScanSearch size={17}/><input placeholder="Search products or brands…" value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{shownCampaigns.length} saved campaigns</span></div>{shownCampaigns.length?<div className="saved-grid">{shownCampaigns.map(c=><article className="saved-card" key={c.id}><div className="saved-cover">{c.creatives[0]&&<img src={c.creatives[0].url} alt={c.name}/>}<span>{c.direction}</span></div><div className="saved-body"><small>{c.brand}</small><h3>{c.name}</h3><p>{c.headline}</p><div className="saved-foot"><span>{c.creatives.length} outputs · {new Date(c.createdAt).toLocaleDateString()}</span><button onClick={()=>{setProduct(c.name);setHeadline(c.headline);setAsset({secure_url:c.assetUrl,public_id:'saved',width:0,height:0,format:'',bytes:0,resource_type:'image'});setUploads(c.creatives);setTab('studio');}}>Open <ArrowRight size={13}/></button></div></div></article>)}</div>:<div className="empty-library"><FolderOpen size={38}/><h3>No saved campaigns yet</h3><p>Generate your first campaign and save it here.</p><button className="btn-primary" onClick={()=>setTab('studio')}>Create first campaign</button></div>}</>}
 {tab==='insights'&&<><PageTitle kicker="CAMPAIGN INTELLIGENCE" title="Know what is ready—and what is not." subtitle="Transparent checks based on your campaign inputs and successful Cloudinary exports."/><div className="intelligence-layout"><div className="readiness-card"><div className="readiness-number"><span>{stats.score}</span><small>/ 100</small></div><h3>Campaign readiness</h3><p>{stats.score===100?'All configured checks have passed.': 'Complete the outstanding checks before publishing.'}</p><div className="progress-track"><i style={{width:`${stats.score}%`}}/></div><small>Deterministic checklist · not an AI-generated score</small></div><Panel title="Preflight audit" subtitle="Each check has an explicit pass / pending state"><div className="audit-list">{stats.checks.map(([label,ok],i)=><div key={label}><span className="audit-index">0{i+1}</span><span><b>{label}</b><small>{ok?'Requirement satisfied':auditHint(i)}</small></span><em className={ok?'pass':'todo'}>{ok?'PASS':'TODO'}</em></div>)}</div></Panel></div><div className="intelligence-note"><ShieldCheck size={18}/><p><b>Honest product intelligence.</b> This version uses observable facts—upload response, entered details, selected channels and completed exports. It does not fabricate visual recognition, image sharpness scores, sentiment analysis or AI model confidence.</p></div></>}
 </div><footer className="footer"><span>LaunchReady AI <b>v5.0</b></span><span>Built around Cloudinary media workflows · Original assets preserved</span><a href="https://cloudinary.com/documentation" target="_blank" rel="noreferrer">Cloudinary docs <Link2 size={12}/></a></footer></section>{busy&&<div className="busy-bar"><LoaderCircle className="spin"/> {progress||'Processing…'}</div>}</main>
}
function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}function slug(s:string){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'campaign';}function auditHint(i:number){return ['Upload a product image to Cloudinary.','Enter a product or campaign name.','Add at least 35 characters of verified product details.','Add your brand name in the product or Brand Kit form.','Select at least three output channels.','Generate and upload every selected creative to Cloudinary.'][i];}
function Metric({icon,label,value,sub}:{icon:ReactNode;label:string;value:string;sub:string}){return <div className="metric-card"><span className="metric-icon">{icon}</span><small>{label}</small><b>{value}</b><em>{sub}</em></div>;}function Module({icon,title,copy,action,onClick,accent}:{icon:ReactNode;title:string;copy:string;action:string;onClick:()=>void;accent:string}){return <button className="module-card" onClick={onClick}><span className={`module-icon ${accent}`}>{icon}</span><h3>{title}</h3><p>{copy}</p><em>{action} <ArrowRight size={14}/></em></button>;}function PageTitle({kicker,title,subtitle}:{kicker:string;title:string;subtitle:string}){return <div className="page-title"><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{subtitle}</p></div>;}function Panel({number,title,subtitle,children}:{number?:string;title:string;subtitle?:string;children:ReactNode}){return <section className="panel"><div className="panel-head">{number&&<span className="step-number">{number}</span>}<div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div></div>{children}</section>;}function Field({label,children,wide}:{label:string;children:ReactNode;wide?:boolean}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{children}</label>;}function BadgeCheck({className}:{className?:string}){return <CheckCircle2 className={className||'green'} size={18}/>;}
